"""empty message

Revision ID: 5dd0385a38c5
Revises: 190b299c7dc7
Create Date: 2021-08-23 12:30:06.984343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5dd0385a38c5'
down_revision = '190b299c7dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('acc_id', sa.String(length=45), nullable=False))
    op.drop_column('user_info', 'acc_ID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('acc_ID', mysql.VARCHAR(length=45), nullable=False))
    op.drop_column('user_info', 'acc_id')
    # ### end Alembic commands ###
