"""empty message

Revision ID: 7092f276b8b4
Revises: 5dd0385a38c5
Create Date: 2021-08-23 17:05:07.966855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7092f276b8b4'
down_revision = '5dd0385a38c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('acc_id', sa.String(length=45), nullable=False))
    op.add_column('user_info', sa.Column('jwt', sa.String(length=300), nullable=True))
    op.drop_column('user_info', 'acc_ID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('acc_ID', mysql.VARCHAR(length=45), nullable=False))
    op.drop_column('user_info', 'jwt')
    op.drop_column('user_info', 'acc_id')
    # ### end Alembic commands ###
