"""empty message

Revision ID: 85deaab7f082
Revises: 58ec02d85ef5
Create Date: 2021-09-24 12:02:10.801054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85deaab7f082'
down_revision = '58ec02d85ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('img_output', sa.Column('pigment_ori', sa.Integer(), nullable=False))
    op.add_column('img_output', sa.Column('pore_ori', sa.Integer(), nullable=False))
    op.add_column('img_output', sa.Column('oily_ori', sa.Integer(), nullable=False))
    op.alter_column('survey_cur_rel', 'cur_kw1_code',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('survey_cur_rel', 'cur_kw2_code',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('total_score_output', sa.Column('total_lvl', sa.String(length=10), nullable=False))
    op.add_column('total_score_output', sa.Column('moisture_lvl', sa.String(length=10), nullable=False))
    op.add_column('total_score_output', sa.Column('pore_lvl', sa.String(length=10), nullable=False))
    op.add_column('total_score_output', sa.Column('oily_lvl', sa.String(length=10), nullable=False))
    op.add_column('total_score_output', sa.Column('pigment_lvl', sa.String(length=10), nullable=False))
    op.add_column('total_score_output', sa.Column('sensitivity_lvl', sa.String(length=10), nullable=False))
    op.alter_column('user_info', 'updated_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_info', 'updated_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('total_score_output', 'sensitivity_lvl')
    op.drop_column('total_score_output', 'pigment_lvl')
    op.drop_column('total_score_output', 'oily_lvl')
    op.drop_column('total_score_output', 'pore_lvl')
    op.drop_column('total_score_output', 'moisture_lvl')
    op.drop_column('total_score_output', 'total_lvl')
    op.alter_column('survey_cur_rel', 'cur_kw2_code',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('survey_cur_rel', 'cur_kw1_code',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('img_output', 'oily_ori')
    op.drop_column('img_output', 'pore_ori')
    op.drop_column('img_output', 'pigment_ori')
    # ### end Alembic commands ###
